name: Checks
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npx hardhat test
      env:
        CI: true
        # These are not needed for the tests but
        # hardhat fails to start when not present.
        NODE_URL_RINKEBY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        NODE_URL_MAINNET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Solhint
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g solhint
      - run: make solhint

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npx hardhat coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  # Security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Slither Static Analysis
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - run: npm install
  #     - run: sudo apt-get install python3-setuptools
  #     - run: wget https://github.com/ethereum/solidity/releases/download/v0.7.6/solc-static-linux && sudo mv solc-static-linux /usr/bin/solc && sudo chmod 744 /usr/bin/solc
  #     - run: git clone https://github.com/crytic/slither.git && cd slither && sudo python3 setup.py install
  #     - run: make slither
  #       env:
  #         # These are not needed for the tests but
  #         # hardhat fails to start when not present.
  #         NODE_URL_RINKEBY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  #         NODE_URL_MAINNET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  #         PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"